apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: api
        tier: backend
        track: stable
    spec:
      containers:
        - name: api
          image: "paruff/customer-service"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"