apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: api
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        tier: frontend
        track: stable
    spec:
      containers:
      - name: client
        image: "paruff/client"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
